apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-final-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tp-final-app
  template:
    metadata:
      labels:
        app: tp-final-app
    spec:
      containers:
        - name: tp-final-app
          image: tp-final-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
